CREATE TABLE KHACHHANG
(
	MAKH INT PRIMARY KEY identity(1,1),
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME
)

CREATE TABLE SANPHAM
(
	MASP INT PRIMARY KEY IDENTITY(1,1),
	TEN nvarchar(50),
	GIA real,
	SL int,
	DANHGIA real,
	DABAN int,
	MOTA nvarchar(100),
	LOAI nvarchar(20),
	ANH image
)

CREATE TABLE LOAISP
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TENLOAI NVARCHAR(20)
)

CREATE TABLE HOADON
(
	SOHD INT PRIMARY KEY IDENTITY(1,1),
	NGHD SMALLDATETIME,
	MAKH INT,
	TRIGIA MONEY
)

CREATE TABLE CTHD
(
	SOHD INT, 
	MASP INT,
	SL INT,
	PRIMARY KEY(SOHD,MASP)
)

ALTER TABLE HOADON ADD CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

ALTER TABLE CTHD ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY(SOHD)
REFERENCES HOADON(SOHD)

ALTER TABLE CTHD ADD CONSTRAINT FK_CTHD_SP FOREIGN KEY(MASP)
REFERENCES SANPHAM(MASP)

SELECT * FROM SANPHAM
SELECT * FROM HOADON
SELECT * FROM CTHD
SELECT * FROM KHACHHANG